name: Publish Docker Image

on:
  release:
    types: [published]
  push:
    tags:
      - 'v*'

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./chaos-agent
          file: ./chaos-agent/Dockerfile
          push: true
          tags: |
            ghcr.io/arihant-dev/chaos-agent:latest
            ghcr.io/arihant-dev/chaos-agent:${{ github.ref_name }}
